version: '2'
services:
    rabbitmq:
        container_name: rabbit
        image: rabbitmq:3-management
        networks:
           reteapp:
            ipv4_address: 172.21.1.2
        ports:
           - "15672:15672"
           - "5672:5672"
    dbprimary:
        container_name: mysqlprimary
        image: mymysql_img:latest
        restart: always
        networks:
           reteapp:
            ipv4_address: 172.21.1.3
        ports:
           - "3307:3306"
    db2:
        container_name: mysql2
        image: mymysql_img:latest
        restart: always
        networks:
           reteapp:
            ipv4_address: 172.21.1.4
        ports:
           - "3308:3306"
    db3:
        container_name: mysql3
        image: mymysql_img:latest
        restart: always
        networks:
           reteapp:
            ipv4_address: 172.21.1.5
        ports:
           - "3309:3306"
    db4:
        container_name: mysql4
        image: mymysql_img:latest
        restart: always
        networks:
           reteapp:
            ipv4_address: 172.21.1.6
        ports:
           - "3310:3306"
    replica2:
          container_name: replica_2
          image: replica2_img:latest
          restart: always
          networks:
             reteapp:
              ipv4_address: 172.21.1.8
          ports:
             - "8082:8080"
             - "4850:4848"
    replica3:
         container_name: replica_3
         image: replica3_img:latest
         restart: always
         networks:
            reteapp:
             ipv4_address: 172.21.1.9
         ports:
            - "8083:8080"
            - "4851:4848"
    replica4:
         container_name: replica_4
         image: replica4_img:latest
         restart: always
         networks:
            reteapp:
             ipv4_address: 172.21.1.10
         ports:
            - "8084:8080"
            - "4852:4848"
    primary:
         container_name: primary
         image: replicaprimary_img:latest
         restart: always
         networks:
            reteapp:
             ipv4_address: 172.21.1.7
         ports: 
            - "8081:8080"
            - "4849:4848"
            - "8182:8181"
    subscriber:
         container_name: subscriberfe
         image: subscriberfe_img:latest
         restart: always
         networks:
            reteapp:
             ipv4_address: 172.21.1.11
         ports:
            - "8087:8080"
    readerfe:
         container_name: readerfe
         image: readerfe_img:latest
         restart: always
         networks:
            reteapp:
             ipv4_address: 172.21.1.12
         ports:
            - "8086:8080"
            - "4853:4848"
            - "8183:8181"
networks:
    reteapp:
     driver: bridge
     ipam:
        config:
           - subnet: 172.21.1.0/24
             gateway: 172.21.1.1
